config/routes.rb
Joeyblog::Application.routes.draw do
    resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def index
		@blogs = Blog.all
	end
  
   def blog_params
    params.require(:blog).permit(:title, :body)
  end
    
  def show
      @blog = Blog.find(params[:id])
  end
    
	def new
		@blog = Blog.new
	end
    
	def create
		@blog = Blog.new(blog_params)
        
		if @blog.save
			redirect_to blogs_path, :notice => "Your blog was created"
       	else
			render "new"
    
  end     
	def edit
       	@blog = Blog.find(params[:id])
  end
        
    def update
     	@blog = Blog.find(params[:id])
            
   	 	if @blog.update_attributes(blog_params)
            redirect_to blogs_path, :notice => "Your post was updated"
    	else
       		render "edit"
  	end
            
    def destroy
    	@blog = Blog.find(params[:id])
                
      @blog.destroy
      redirect_to blogs_path, :notice => "Your post was deleted"
    end
   	end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<h1>Edit Blog Post</h1>
<%= form_for @blog do |f| %>
	<p>
		<%= f.label :title %>: <%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %>: <%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit "update blog post"  %>
		</p>
<% end %>

app/views/blogs/index.html.erb
<h1>Blog Posts</h1>
<% @blogs.each do |blog| %>	
	<h2><%= link_to blog.title, blog %></h2>
	<p><%= blog.body %></p>
<% end %>

<p><%= link_to "New Blog Post", new_blog_path %></p>

app/views/blogs/new.html.erb
<h1>New Blog Post</h1>
<%= form_for @blog do |f| %>
	<p>
		<%= f.label :title %>: <%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %>: <%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit "Add New Blog Post" %>
	</p>
<% end %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>
<p><%= @blog.body %></p>
<p><%= @blog.created_at %></p>
<p>
<%= link_to "Edit", edit_blog_path(@blog) %>  ::
<%= link_to "Delete", @blog, :confirm => "Are you sure?", :method => :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joeyblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
<p><%= value %></p>
<% end %>

<%= yield %>

</body>
</html>